# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: read

jobs:
  build:
    defaults:
        run:
          working-directory: ./web
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npx pnpm install
    - run: npm run build --if-present
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.3
      with:
        author_name: vg2-auto
        author_email: vgounden@gmail.com
        message: Auto update
        new_branch: gh-pages
        push: origin gh-pages --set-upstream --force
